name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish src/PrismaPrimeInvest.Api/PrismaPrimeInvest.Api.csproj --configuration Release --output ./publish

      - name: Deploy to Azure Web App
        uses: Azure/webapps-deploy@v2
        with:
          app-name: 'prisma-prime-invest-ep'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: './publish'
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.AZURE_CONNECTION_STRING }}

      - name: Apply database migrations
        run: dotnet ef database update --project src/PrismaPrimeInvest.Infra.Data -s src/PrismaPrimeInvest.Api -c ApplicationDbContext
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.AZURE_CONNECTION_STRING }}
