name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main  # Aciona o workflow quando houver um push na branch main
  pull_request:
    branches:
      - main  # Aciona o workflow quando houver um PR para a branch main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'  # Defina a versão do .NET que você está usando

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish src/PrismaPrimeInvest.Api/PrismaPrimeInvest.Api.csproj --configuration Release --output ./publish

      - name: Deploy to Azure Web App
        uses: Azure/webapps-deploy@v2
        with:
          app-name: 'api-prisma-prime-invest'  # Substitua pelo nome do seu Web App
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # O perfil de publicação do Azure
          package: './publish'  # O caminho para o pacote a ser implantado
